language: java
script: mvn -f teachus-parent/pom.xml test
jdk:
  - openjdk6
before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS teachus_test;"
  - mysql -e "CREATE USER 'teachus_build'@'localhost' IDENTIFIED BY 'teachus_build';"
  - mysql -u root -e "GRANT ALL ON teachus_test.* TO 'teachus_build'@'localhost';"
branches:
  only:
    - master