ALTER TABLE
	application_configuration
	MODIFY COLUMN
		version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE
	booking
	MODIFY COLUMN
		version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE
	period
	MODIFY COLUMN
		version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE
	person
	MODIFY COLUMN
		version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE
	teacher_attribute
	MODIFY COLUMN
		version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE
	message
	MODIFY COLUMN
		version INTEGER NOT NULL DEFAULT 0;

-- Upgrade version
UPDATE
	application_configuration 
SET
	`value`='1.53'
WHERE
	name='VERSION';
